# Assignment

### Importing libraries for the (Exploratory Data Analysis) EDA.

In [1]:
import pandas as pd
import numpy as np

### Loading the dataset

In [2]:
df = pd.read_csv("aps_failure_set.csv")

In [3]:
df

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,na,2130706438,280,0,0,0,0,0,...,1240520,493384,721044,469792,339156,157956,73224,0,0,0
1,neg,33058,na,0,na,0,0,0,0,0,...,421400,178064,293306,245416,133654,81140,97576,1500,0,0
2,neg,41040,na,228,100,0,0,0,0,0,...,277378,159812,423992,409564,320746,158022,95128,514,0,0
3,neg,12,0,70,66,0,10,0,0,0,...,240,46,58,44,10,0,0,0,4,32
4,neg,60874,na,1368,458,0,0,0,0,0,...,622012,229790,405298,347188,286954,311560,433954,1218,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,neg,153002,na,664,186,0,0,0,0,0,...,998500,566884,1290398,1218244,1019768,717762,898642,28588,0,0
59996,neg,2286,na,2130706538,224,0,0,0,0,0,...,10578,6760,21126,68424,136,0,0,0,0,0
59997,neg,112,0,2130706432,18,0,0,0,0,0,...,792,386,452,144,146,2622,0,0,0,0
59998,neg,80292,na,2130706432,494,0,0,0,0,0,...,699352,222654,347378,225724,194440,165070,802280,388422,0,0
59999,neg,40222,na,698,628,0,0,0,0,0,...,440066,183200,344546,254068,225148,158304,170384,158,0,0

### Analyzing the size of the dataset

In [4]:
num_rows, num_columns = df.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 60000
Number of columns: 171

### Checking details of each column (datatype, number of null entries etc)

In [5]:
for column in df.columns:
    df[column].info()

<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: class
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: aa_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  int64
dtypes: int64(1)
memory usage: 468.9 KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ab_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ac_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ad_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ae_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: af_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ag_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ah_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ai_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: aj_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ak_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: al_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: am_0
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: an_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ao_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ap_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: aq_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ar_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: as_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: at_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: au_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: av_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ax_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ay_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: az_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ba_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bb_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bc_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bd_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: be_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bf_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bg_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bh_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bi_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bj_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bk_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bl_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bm_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bn_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB

<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bo_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bp_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bq_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: br_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bs_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bt_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bu_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bv_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bx_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: by_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bz_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ca_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cb_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cc_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cd_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ce_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cf_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cg_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ch_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ci_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cj_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ck_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cl_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cm_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cn_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: co_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cp_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cq_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cr_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cs_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ct_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cu_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cv_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cx_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cy_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: cz_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: da_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: db_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dc_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dd_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: de_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: df_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dg_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dh_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: di_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dj_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dk_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dl_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dm_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dn_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: do_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dp_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dq_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dr_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ds_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dt_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: du_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dv_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dx_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dy_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: dz_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ea_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: eb_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ec_00
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ed_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_001
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_002
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_003
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_004
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_005
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_006
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_007
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_008
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ee_009
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ef_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: eg_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB

### Checking for missing values exclusively for each column

In [6]:
missing_values = df.isnull().sum()
print("Missing values per attribute:")
print(missing_values)

Missing values per attribute:
class     0
aa_000    0
ab_000    0
ac_000    0
ad_000    0
         ..
ee_007    0
ee_008    0
ee_009    0
ef_000    0
eg_000    0
Length: 171, dtype: int64

### Significant findings from preprocessing of data:
 - The size(shape) of the dataset helps you understand the data's volume.
 - Getting to know the datatypes of each feature can give you an idea of how to precede further calculations and manipulations of data.
 - Missing values indicate potential data quality issues that may require handling. Fortunately, no missing values found in any columns so no need to handle them.
 - The feature whose datatype is numerical is only 'aa_000'.

In [7]:
df.describe()

             aa_000
count  6.000000e+04
mean   5.933650e+04
std    1.454301e+05
min    0.000000e+00
25%    8.340000e+02
50%    3.077600e+04
75%    4.866800e+04
max    2.746564e+06

### Enhancing EDA (Exploratory Data Analysis) with visualization of data.
- Importing vital libraries for visualization

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df['class'].value_counts()

class
neg    59000
pos     1000
Name: count, dtype: int64

- Histogram Plot

## Curse of Dimensionality
The Curse of Dimensionality refers to the challenges and problems that arise when dealing with high-dimensional data. It affects data analysis as follows:
 - As the number of dimensions increases, algorithms require more computational resources.
 - High-dimensional data can lead to overfitting in machine learning models.
 - It becomes harder to infer meaningful patterns with many dimensions.
 - Data points become more spread out, making it challenging to find neighbors or similarities.

One of the solutions to this curse is dimensionality reduction and this could be achieved by applying Principal Component Analysis (PCA) on dataset.

## Applying Principal Component Analysis (PCA) for Dimensionality Reduction.

### Importing necessary Libraries for PCA

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

### Applying label encoding on dataset to convert categorical features (string) to numerical classes. This is done to incorporate the whole data for further calculations

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform(df[i])

### Standardization (mean centering and scaling to unit variance). Standardization ensures that all features have equal influence in the PCA analysis, and it helps in capturing the true variance of each feature.

In [13]:
scaler = StandardScaler()
data_standardized = scaler.fit_transform(df)
data_standardized

array([[-0.13018891,  1.19159108,  0.53075991, ..., -0.73351866,
        -0.22474038, -0.23069838],
       [-0.13018891, -0.00875114,  0.53075991, ..., -0.18281782,
        -0.22474038, -0.23069838],
       [-0.13018891,  0.36900137,  0.53075991, ...,  1.47847888,
        -0.22474038, -0.23069838],
       ...,
       [-0.13018891, -1.03091398, -1.98735109, ..., -0.73351866,
        -0.22474038, -0.23069838],
       [-0.13018891,  1.26738608,  0.53075991, ...,  1.12466072,
        -0.22474038, -0.23069838],
       [-0.13018891,  0.30802918,  0.53075991, ..., -0.11116648,
        -0.22474038, -0.23069838]])

### Applying PCA to transform the original data into a new set of orthogonal features (principal components) that explain the most variance in the data.

In [14]:
pca = PCA()
pca.fit(data_standardized)

PCA()

### Calculating the explained variance ratio tells us the proportion of the total variance in the data that is explained by each principal component, helping to understand the significance of each component.

In [15]:
explained_variance_ratio = pca.explained_variance_ratio_
explained_variance_ratio

array([1.33244725e-01, 6.79023540e-02, 5.93759898e-02, 4.96641181e-02,
       4.37523483e-02, 2.80370345e-02, 2.39090446e-02, 1.93514205e-02,
       1.69558886e-02, 1.42395333e-02, 1.37942134e-02, 1.22897537e-02,
       1.05263495e-02, 9.80522173e-03, 9.20516074e-03, 8.75267476e-03,
       8.37485445e-03, 8.27254678e-03, 7.76212003e-03, 7.57683685e-03,
       7.36066150e-03, 7.00418788e-03, 6.89101202e-03, 6.72106157e-03,
       6.38597174e-03, 6.29711295e-03, 6.13235750e-03, 6.06363742e-03,
       5.92637585e-03, 5.86462146e-03, 5.78668830e-03, 5.68400381e-03,
       5.58745557e-03, 5.55749602e-03, 5.49435565e-03, 5.39396148e-03,
       5.36021889e-03, 5.30258710e-03, 5.27876865e-03, 5.23287794e-03,
       5.16048310e-03, 5.11422473e-03, 5.05415365e-03, 5.00953699e-03,
       4.92879615e-03, 4.88535759e-03, 4.87263221e-03, 4.81969957e-03,
       4.80955745e-03, 4.69762761e-03, 4.65652734e-03, 4.60889029e-03,
       4.55634816e-03, 4.51717147e-03, 4.49225120e-03, 4.48047143e-03,
       4.41373854e-03, 4.38127991e-03, 4.32542962e-03, 4.29044471e-03,
       4.25537226e-03, 4.22220720e-03, 4.16593664e-03, 4.10374458e-03,
       4.08123439e-03, 4.03873468e-03, 3.98925065e-03, 3.94704937e-03,
       3.90671221e-03, 3.88350934e-03, 3.83981293e-03, 3.82489254e-03,
       3.81174703e-03, 3.78959660e-03, 3.68145222e-03, 3.65463145e-03,
       3.61559704e-03, 3.58162864e-03, 3.54976834e-03, 3.50875179e-03,
       3.50061378e-03, 3.44076267e-03, 3.39740863e-03, 3.37497941e-03,
       3.35571524e-03, 3.31131880e-03, 3.27739302e-03, 3.27030508e-03,
       3.22405364e-03, 3.19751709e-03, 3.17821593e-03, 3.13824384e-03,
       3.12863160e-03, 3.10525165e-03, 3.03907518e-03, 3.03008880e-03,
       2.98772122e-03, 2.97677517e-03, 2.94777911e-03, 2.92724140e-03,
       2.88212106e-03, 2.87580486e-03, 2.82729430e-03, 2.79218805e-03,
       2.76284076e-03, 2.72252644e-03, 2.68234253e-03, 2.62394610e-03,
       2.61089451e-03, 2.53609477e-03, 2.52591891e-03, 2.47463381e-03,
       2.43971268e-03, 2.41249375e-03, 2.32315240e-03, 2.30925662e-03,
       2.20428539e-03, 2.11705248e-03, 2.08774630e-03, 1.95991126e-03,
       1.93288910e-03, 1.88995942e-03, 1.86957952e-03, 1.81723344e-03,
       1.78461838e-03, 1.76535064e-03, 1.68604217e-03, 1.67122276e-03,
       1.63253559e-03, 1.61163816e-03, 1.50758377e-03, 1.47355166e-03,
       1.42796882e-03, 1.39392819e-03, 1.37284327e-03, 1.29195563e-03,
       1.22604726e-03, 1.12254081e-03, 1.09960114e-03, 1.04078519e-03,
       1.02794042e-03, 9.48308105e-04, 9.26749591e-04, 8.53658012e-04,
       8.03803724e-04, 7.23931555e-04, 7.03234117e-04, 6.59019635e-04,
       6.18483346e-04, 5.34513945e-04, 4.99920943e-04, 4.70354916e-04,
       4.41165527e-04, 4.09133553e-04, 2.73023025e-04, 2.66708909e-04,
       2.35412744e-04, 2.22919111e-04, 2.05211908e-04, 2.01629237e-04,
       1.55553021e-04, 1.42353254e-04, 1.32406743e-04, 9.54031244e-05,
       8.05968940e-05, 4.99570429e-05, 3.74855473e-05, 2.77828564e-05,
       1.23024181e-05, 1.75739620e-11, 4.81002416e-12])

### By calculating the cumulative explained variance, we can determine the number of components required to retain a certain percentage of the total variance. In this case, we aim to retain 99.5% (as mentioned in assignment) of the variance, which balances dimensionality reduction and information preservation.

In [16]:
cumulative_explained_variance = np.cumsum(explained_variance_ratio)
num_components = np.argmax(cumulative_explained_variance >= 0.995) + 1
num_components

149

### Applying PCA on selected most significant components can lead to improved model performance, faster training times, and easier data interpretation.

In [17]:
pca = PCA(n_components=num_components)
data_reduced = pca.fit_transform(data_standardized)
data_reduced

array([[-3.30051431e-01,  1.90013155e-01, -2.47802259e+00, ...,
         1.43427963e-01, -5.12026333e-02, -1.81855258e-01],
       [ 9.88169318e-01, -5.72873802e-01, -5.56483540e+00, ...,
        -7.82852201e-02, -1.72154588e-02, -8.79750004e-02],
       [-3.51275762e+00, -3.48239574e-02, -9.40571863e-01, ...,
         1.55459322e-01, -9.05344745e-02, -4.27545254e-02],
       ...,
       [-1.09584681e+00,  4.55045208e-01,  4.46099209e+00, ...,
        -6.33088373e-02,  2.07164128e-01, -2.81228612e-01],
       [-7.40064322e-01,  3.89020552e-01, -1.41326726e+00, ...,
         4.11290980e-02,  1.24662174e-01, -6.43678849e-01],
       [-1.76892405e+00,  5.64375980e-01, -2.24915358e+00, ...,
         4.54404419e-03,  9.11644847e-02,  1.56842807e-02]])

## Results of PCA

In [18]:
print(f"Explained Variance Ratio: {explained_variance_ratio}")
print(f"Number of Components to Retain 99.5% Variance: {num_components}")
print(f"Reduced Data Shape: {data_reduced.shape}")

Explained Variance Ratio: [1.33244725e-01 6.79023540e-02 5.93759898e-02 4.96641181e-02
 4.37523483e-02 2.80370345e-02 2.39090446e-02 1.93514205e-02
 1.69558886e-02 1.42395333e-02 1.37942134e-02 1.22897537e-02
 1.05263495e-02 9.80522173e-03 9.20516074e-03 8.75267476e-03
 8.37485445e-03 8.27254678e-03 7.76212003e-03 7.57683685e-03
 7.36066150e-03 7.00418788e-03 6.89101202e-03 6.72106157e-03
 6.38597174e-03 6.29711295e-03 6.13235750e-03 6.06363742e-03
 5.92637585e-03 5.86462146e-03 5.78668830e-03 5.68400381e-03
 5.58745557e-03 5.55749602e-03 5.49435565e-03 5.39396148e-03
 5.36021889e-03 5.30258710e-03 5.27876865e-03 5.23287794e-03
 5.16048310e-03 5.11422473e-03 5.05415365e-03 5.00953699e-03
 4.92879615e-03 4.88535759e-03 4.87263221e-03 4.81969957e-03
 4.80955745e-03 4.69762761e-03 4.65652734e-03 4.60889029e-03
 4.55634816e-03 4.51717147e-03 4.49225120e-03 4.48047143e-03
 4.41373854e-03 4.38127991e-03 4.32542962e-03 4.29044471e-03
 4.25537226e-03 4.22220720e-03 4.16593664e-03 4.10374458e-03
 4.08123439e-03 4.03873468e-03 3.98925065e-03 3.94704937e-03
 3.90671221e-03 3.88350934e-03 3.83981293e-03 3.82489254e-03
 3.81174703e-03 3.78959660e-03 3.68145222e-03 3.65463145e-03
 3.61559704e-03 3.58162864e-03 3.54976834e-03 3.50875179e-03
 3.50061378e-03 3.44076267e-03 3.39740863e-03 3.37497941e-03
 3.35571524e-03 3.31131880e-03 3.27739302e-03 3.27030508e-03
 3.22405364e-03 3.19751709e-03 3.17821593e-03 3.13824384e-03
 3.12863160e-03 3.10525165e-03 3.03907518e-03 3.03008880e-03
 2.98772122e-03 2.97677517e-03 2.94777911e-03 2.92724140e-03
 2.88212106e-03 2.87580486e-03 2.82729430e-03 2.79218805e-03
 2.76284076e-03 2.72252644e-03 2.68234253e-03 2.62394610e-03
 2.61089451e-03 2.53609477e-03 2.52591891e-03 2.47463381e-03
 2.43971268e-03 2.41249375e-03 2.32315240e-03 2.30925662e-03
 2.20428539e-03 2.11705248e-03 2.08774630e-03 1.95991126e-03
 1.93288910e-03 1.88995942e-03 1.86957952e-03 1.81723344e-03
 1.78461838e-03 1.76535064e-03 1.68604217e-03 1.67122276e-03
 1.63253559e-03 1.61163816e-03 1.50758377e-03 1.47355166e-03
 1.42796882e-03 1.39392819e-03 1.37284327e-03 1.29195563e-03
 1.22604726e-03 1.12254081e-03 1.09960114e-03 1.04078519e-03
 1.02794042e-03 9.48308105e-04 9.26749591e-04 8.53658012e-04
 8.03803724e-04 7.23931555e-04 7.03234117e-04 6.59019635e-04
 6.18483346e-04 5.34513945e-04 4.99920943e-04 4.70354916e-04
 4.41165527e-04 4.09133553e-04 2.73023025e-04 2.66708909e-04
 2.35412744e-04 2.22919111e-04 2.05211908e-04 2.01629237e-04
 1.55553021e-04 1.42353254e-04 1.32406743e-04 9.54031244e-05
 8.05968940e-05 4.99570429e-05 3.74855473e-05 2.77828564e-05
 1.23024181e-05 1.75739620e-11 4.81002416e-12]
Number of Components to Retain 99.5% Variance: 149
Reduced Data Shape: (60000, 149)

## Summary
Principal Component Analysis (PCA) is a popular linear feature extractor used for unsupervised feature selection. PCA is used for dimensionality reduction in this analysis because it offers several benefits:

- **Reduced Dimensionality:** PCA transforms high-dimensional data into a lower-dimensional space while preserving as much variance as possible.
- **Improved Model Performance:** In many cases, reducing dimensionality with PCA can lead to better performance in machine learning models, as it reduces noise and multicollinearity.

By performing PCA and retaining 99.5% of the variance, we are ensuring that the most critical information is retained while reducing the data's complexity. The result, **data_reduced**, contains a reduced set of features that are most informative for further analysis or modeling.

## References

1. Scikit-learn Contributors. "Scikit-learn: Machine Learning in Python." [Scikit-learn Website](https://scikit-learn.org/stable/)

2. Seaborn Development Team. "Seaborn: Statistical Data Visualization." [Seaborn Website](https://seaborn.pydata.org/)

3. Matplotlib Development Team. "Matplotlib: Visualization with Python." [Matplotlib Website](https://matplotlib.org/)

4. Numpy Development Team. "Numpy: Scientific Computing." [Numpy Website](https://numpy.org//)

5. Pandas Development Team. "Pandas: Powerful data structures for data analysis, time series, and statistics." [Pandas Website](https://pandas.pydata.org/)